---
- name: generate ssh key
  user: name=$user generate_ssh_key=yes

- name: setup django development server as a service
  template: src='django-devserver.conf.j2' dest='/etc/init/django-devserver.conf'
  notify:
    restart webserver

- name: install deploy_dreamhost
  template: src='deploy_dreamhost.sh.j2' dest='$scripts_dir/deploy_dreamhost.sh' mode=0755

- name: copy dev_requirements
  copy: src='dev_requirements.txt' dest='$home/dev_requirements.txt'

- name: install dev_requirements
  sudo: no
  pip: requirements='$home/dev_requirements.txt' virtualenv=$virtualenv state=latest

- name: install libfontconfig which is needed by phantomjs
  apt: pkg=libfontconfig1 state=latest

- name: ensure add-apt-repository command
  apt: pkg=python-software-properties state=latest

- name: setup nodejs ppa
  apt_repository: repo='ppa:chris-lea/node.js'

- name: install nodejs
  apt: pkg=nodejs state=latest update_cache=yes

- name: install development tools
  npm: name=$item global=yes state=present
  with_items:
    - less
    - phantomjs
    - karma
    - karma-coverage
