- hosts: dreamhost
  user: $user
  sudo: no

  pre_tasks:
    - name: ensure latest hutmap code
      git: repo=git://github.com/dylanfprice/hutmap.git
           dest=$repo_dir
           update=yes
      tags:
        - partial

  roles:
    - pyenv
    - webserver

  tasks:
    # - TODO: [hutmap] ensure geos and gdal libs

    - name: install passenger_wsgi.py
      template: src='templates/passenger_wsgi.py.j2' dest='$repo_dir/passenger_wsgi.py'

    - name: update static files
      local_action: shell . \$HOME/.bash_profile && 
        workon_hutmap && 
        HUTMAP_DEBUG=${hutmap.debug} HUTMAP_VERSION=${hutmap.version}
        python manage.py $item
      with_items:
        - collectstatic --noinput -i '*.less' -i 'js-test'
        - compress -f
      tags:
        - partial

    - name: upload static files
      local_action: command rsync -ae ssh --exclude 'data' /vagrant/public/static $user@$inventory_hostname:$public_dir
      notify:
        - restart webserver
      tags:
        - partial

    - name: migrate db
      shell: . \$HOME/.bash_profile &&
        workon_hutmap &&
        python manage.py $item
      with_items:
        - syncdb --noinput
        - migrate --noinput huts
      tags:
        - partial

  handlers:
    - name: restart webserver
      shell: /usr/bin/pkill -f phusion_passenger
      ignore_errors: True
