---
- hosts: vagrant
  user: '{{ user }}'
  sudo: yes

  roles: 
    - mysql
    - webserver_base
    - webserver
    - dev

  tasks:
    - name: update locale to utf-8
      command: /usr/sbin/update-locale LANGUAGE=en_US.utf8 LANG=en_US.utf8 LC_ALL=en_US.utf8 

    - name: install geodjango libs
      apt: pkg={{ item }} state=present
      with_items:
        - libgeos-c1
        - libgdal1-1.7.0


