Vagrant::Config.run do |config|
  config.vm.box = 'lucid32'
  config.vm.forward_port 80, 8080
  config.vm.share_folder "hutmap", "/vagrant", ".."
  #config.vm.boot_mode = :gui

  # Enable and configure the chef solo provisioner
  config.vm.provision :chef_solo do |chef|
    chef.add_recipe('hutmap_main')
    chef.json = {
      :mysql => {
        :server_debian_password => 'debian',
        :server_root_password   => 'vagrant',
        :server_repl_password   => 'repl',
      },
      :usr_libs => '/usr/local/lib',
    }
    # Pass on hutmap env vars
    ENV.each do |key, value|
      if key.start_with?("HUTMAP")
        chef.json[key.to_sym] = value
      end
    end
  end
end
